# Values used for the deployed application.
replicaCount: 1
service:
  name: factset-reader
env:
  FACTSET_FTP: fts-sftp.factset.com
resources:
  limits:
    memory: 256Mi
storage:
  region: eu-west-1
  zone: eu-west-1b
  capacity: 5Gi
  fsType: ext4
  volumeID: vol-0f5b81792099179d3
