kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.service.name }}-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
  selector:
    matchLabels:
      provisioned-for: "{{.Values.service.name}}"
